Traceback (most recent call last):
  File "main.pyw", line 52, in <module>
IndexError: list index out of range
